apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: CLUSTER
  region: AWS_DEFAULT_REGION
fargateProfiles:
  - name: XFARGATENAME
    podExecutionRoleARN: arn:aws:iam::XACCOUNT:role/AmazonEKSFargatePodExecutionRole
    selectors:
    - namespace: XNSPACE
    subnets:
    - XSUBNET1
    - XSUBNET2
