#!/bin/bash


listProject(){
  aws codebuild list-projects --output json |jq -r '.projects[]'
}

listPattern(){
  cat $0 |grep "  \--" |sed 's/\#//g;s/)//g;s/\"//g'
}

createWebhook() {
  JSONFILE=`cat template/webhook.json |sed "s/XPROJECT/$PROJECT/g"` 
  echo $JSONFILE > webhook-$PROJECT.json
  aws codebuild create-webhook --cli-input-json file://webhook-$PROJECT.json --no-cli-auto-prompt
  rm -rf webhook-$PROJECT.json
}

command=$1

case $command in
  --build-one)          #Build Project
    PROJECT=$2
    aws codebuild start-build --project-name $PROJECT
  ;;
  --list-all)           #List Project
    aws codebuild list-projects --output json |jq -r '.projects[]'
  ;;
  --export-all)         #Export All Codebuild Project
        echo "--- Backup to folder $(date +%d%m%Y)-json ---"
        mkdir -p $(date +%d%m%Y)-json json
        arr=( `aws codebuild list-projects --output json |jq -r '.projects[]'`)
        for i in ${arr[@]}
        do
            aws codebuild batch-get-projects --names $i --output json |jq -r '.projects[]' > $(date +%d%m%Y)-json/$i.json
        done

        rm -rf json/*
        echo "--- Create Clean JSON to folder json ---"
        for i in ${arr[@]}
        do
            jq 'del(.arn,.webhook,.created,.lastModified,.badge)' $(date +%d%m%Y)-json/$i.json > json/$i.json
        done
    ;;
  --create-webhook)     #Create auto build trigger webhook on project
    PROJECT=$2
    createWebhook

    ;;
  --delete-webhook)     #Delete webhook on project
    aws codebuild delete-webhook --project-name $2
    ;;

  --create-new)         #Create New Project include webhook
    PROJECT=$2
    aws codebuild create-project --cli-input-json file://json/$PROJECT.json
    createWebhook
    ;;
    
  --update-one)         #Update project
    PROJECT=$2
    aws codebuild update-project --cli-input-json file://json/$PROJECT.json

    ;;

  --delete-one)         #Delete project
    PROJECT=$2
    aws codebuild delete-project --name $PROJECT
    ;;
  *)
echo "arg required"
echo "---"
echo " "
echo "  Command Tools base on AWS Command For Codebuild"
echo "
LIST 'PROJECT NAME':

$(listProject)

AVAILABLE 'ARG':

$(listPattern)

USAGE:
$0 <ARG> <PROJECT NAME>
"
    ;; 
esac




